### ISSUE TITLE
cdb release

### ISSUE THREAD

**Issue by BuckarooBanzay** [mt-mods/fakeplayer#2]
* [ ] screenshot
* [ ] add to cdb

**Comment by OgelGames** [comment]
I'm working on my `fakelib` mod again, this mod will be obsolete once that is finished, best not to put this on CDB.

**Comment by S-S-X** [comment]
Personally I'd prefer one under community organization and with open development from beginning. Maybe @OgelGames you could consider integrating your improvements here instead of starting new personal project for it.

**Comment by OgelGames** [comment]
> instead of starting new personal project for it

Too late for that, I started it a long time ago and I'm going to finish it :D

**Comment by BuckarooBanzay** [comment]
> I'm working on my fakelib mod again, this mod will be obsolete once that is finished, best not to put this on CDB.

ok then, i think we can wait, no pressure  :+1:

**Comment by OgelGames** [comment]
I have completed `fakelib`, and it is available on ContentDB (https://content.minetest.net/packages/OgelGames/fakelib), so this mod can be deleted now.

**Comment by BuckarooBanzay** [comment]
> I have completed `fakelib`, and it is available on ContentDB (https://content.minetest.net/packages/OgelGames/fakelib), so this mod can be deleted now.

nice, thanks for your work :tada:
